Update recordTrimEdit.py (test #11)
carykh/recordTrimEdit pull request #14
Opened 2024-03-15 15:54 UTC by Afonsobrasil

# Error solving( test warning )
This is in test, so this dont work
Also, soon if it rlly dont work, i'll update it.
this is made due to the issue 11.

2024-03-15 16:10 UTC, Afonsobrasil commented
i added a if to looks great.

2024-03-15 17:45 UTC, ben9583 requested changes
This is a cool feature! There are a handful of issues here and I get the sense you haven't run this before (line 36 is a syntax error). Please test this yourself after fixing the errors and get back to me here

2024-03-15 17:45 UTC, ben9583 commented on recordTrimEdit.py
> +try:
Is there any particular reason this would fail?

2024-03-15 17:45 UTC, ben9583 commented on recordTrimEdit.py
> +
formatting

2024-03-15 18:59 UTC, Afonsobrasil commented
Ok, i'll test it.

2024-03-16 16:52 UTC, Afonsobrasil commented
It is really taking more than i thinked. Hope i fix it.

2024-03-16 17:10 UTC, Afonsobrasil commented
I'll commit it and you test the code. I think that is my mic is really bad.

2024-03-16 19:15 UTC, Afonsobrasil commented
FINISHED! Error #6 is not letting it be  100% complete, but accept this, that i'll fix it.

2024-03-16 19:21 UTC, Afonsobrasil commented
Also there was an error in recordTrimEdit that dont let it open.
i fixed it lol

2024-03-16 19:23 UTC, Afonsobrasil reviewed
All done

2024-03-18 20:04 UTC, ben9583 commented
I think whatever it is you're doing with the `try...except` block on the import and the changes to config loading is beyond the scope of this issue, so I'll be removing it for now but feel free to create a separate PR for those changes

2024-04-05 15:47 UTC, closed without merging